// Client-side search over the prebuilt index in /public/data.
//
// The index is generated by scripts/search-index.mjs, which encodes each
// article as a tuple to keep the file small. decodeItem below is the other
// half of that contract — change one and you must change the other.

import { fetchJSON } from '@/lib/data';

export interface SearchMovement {
  id: string;
  name: string;
  location: string;
  description: string;
}

/** [movementIndex, title, source, date, excerpt?] */
type RawItem = [number, string, string, string, string?];

interface RawIndex {
  generated: string;
  movements: SearchMovement[];
  items: RawItem[];
}

export interface SearchHit {
  /** Position in the index, and so the position of this article's URL. */
  ref: number;
  title: string;
  source: string;
  date: string;
  excerpt: string;
  movement: SearchMovement;
}

export interface SearchIndex {
  generated: string;
  movements: SearchMovement[];
  hits: SearchHit[];
}

export interface SearchResults {
  movements: SearchMovement[];
  articles: SearchHit[];
  /** Total article matches, of which `articles` is the first page. */
  total: number;
}

let cached: Promise<SearchIndex | null> | null = null;
let cachedUrls: Promise<string[]> | null = null;

function decodeItem(raw: RawItem, ref: number, movements: SearchMovement[]): SearchHit | null {
  const movement = movements[raw[0]];
  if (!movement) return null;
  return {
    ref,
    title: raw[1],
    source: raw[2],
    date: raw[3],
    excerpt: raw[4] || '',
    movement,
  };
}

/**
 * Load and decode the index. Memoised: the header dropdown and the search
 * page both call this, and neither should pay for the fetch twice.
 */
export function loadSearchIndex(): Promise<SearchIndex | null> {
  if (!cached) {
    cached = fetchJSON<RawIndex>('search-index.json').then((raw) => {
      if (!raw || !Array.isArray(raw.items)) return null;
      const movements = raw.movements || [];
      const hits: SearchHit[] = [];
      raw.items.forEach((item, i) => {
        const hit = decodeItem(item, i, movements);
        if (hit) hits.push(hit);
      });
      return { generated: raw.generated, movements, hits };
    });
  }
  return cached;
}

/**
 * Article hrefs, positionally aligned with the index. Kept in a separate
 * file because Google News ids dwarf everything else, and only a page that
 * actually renders outbound links needs them.
 */
export function loadSearchUrls(): Promise<string[]> {
  if (!cachedUrls) {
    cachedUrls = fetchJSON<string[]>('search-urls.json').then((raw) =>
      Array.isArray(raw) ? raw : [],
    );
  }
  return cachedUrls;
}

// Every term must appear somewhere in the record, in any order and in any
// field — "kenya tax" finds a Nation piece on the tax bill without the
// reader having to guess the headline's wording.
function terms(query: string): string[] {
  return query.toLowerCase().split(/\s+/).filter(Boolean);
}

function matchesAll(haystack: string, needles: string[]): boolean {
  return needles.every((n) => haystack.includes(n));
}

/**
 * How well a record answers the query, so that a search for "fuel subsidy"
 * leads with headlines about it rather than with every article filed under
 * the movement of that name — which all match on the movement field alone.
 * 0 means no match.
 */
function score(hit: SearchHit, words: string[]): number {
  const title = hit.title.toLowerCase();
  const own = `${title} ${hit.source.toLowerCase()} ${hit.excerpt.toLowerCase()}`;
  const all = `${own} ${hit.movement.name.toLowerCase()}`;
  if (!matchesAll(all, words)) return 0;
  if (matchesAll(title, words)) return 3;
  if (matchesAll(own, words)) return 2;
  return 1;
}

export function search(index: SearchIndex | null, query: string, limit = 50): SearchResults {
  const words = terms(query);
  if (!index || words.length === 0) return { movements: [], articles: [], total: 0 };

  const movements = index.movements.filter((m) =>
    matchesAll(`${m.name} ${m.location} ${m.description}`.toLowerCase(), words),
  );

  const scored: { hit: SearchHit; score: number }[] = [];
  for (const hit of index.hits) {
    const s = score(hit, words);
    if (s > 0) scored.push({ hit, score: s });
  }

  // hits arrive newest-first, and sort is stable, so equally relevant
  // records stay in date order.
  scored.sort((a, b) => b.score - a.score);

  return {
    movements,
    articles: scored.slice(0, limit).map((s) => s.hit),
    total: scored.length,
  };
}
